name: puffy_playground

description: Playground Flutter project.

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  frock:
    path: xpackages/frock
  async: ^2.8.1
  provider: ^6.0.2
  package_info_plus: ^1.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
